print('Olá, mundo')
print('estou ótima hoje')
print('hoje está muito calor')
print('quero férias')
print('o clima está péssimo')
print('estou com fome')
print('amo frio')
print('amo meu namorado')
print('quero coxinha')
print('quero minha casa')